name: WorldManager
version: 2.0.1
authors: [ Hakuyamu ]
main: de.leonheuer.worldmanager.WorldManager
api-version: 1.18
depend: [ Multiverse-Core ]
softdepend: [ SkyBeeCore ]

commands:
  worldmanager:
    aliases: [ wm ]
    permission: worldmanager.command

permissions:
  worldmanager.bypass:
    break:
      description: bypass break flag
    ignite:
      description: bypass ignite flag
    place:
      description: bypass place flag
    forbidden:
      description: bypass forbidden flag
    pvp:
      description: bypass pvp flag
    pve:
      description: bypass pve flag
    bucket:
      description: bypass bucket flag
    interact:
      description: bypass interact flag
    vehicle:
      description: bypass vehicle flag